name: "Build docker image"

on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-compose.yaml'

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Running this job only for main branch
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Publish Docker image
        run: |
              docker build . -t ghcr.io/pinisok/gakutoolkit:latest -f Dockerfile
              docker push ghcr.io/pinisok/gakutoolkit:latest